version: 2

sources:
  - name: adventureworks
    database: postgres
    schema: public

    tables:
      - name: fact_internet_sales
      - name: dim_product
      - name: dim_product_category
      - name: dim_product_subcategory
